// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['services']['CategoryService']['CreateCategory'](arg1);
}

export function DeleteCategory(arg1, arg2) {
  return window['go']['services']['CategoryService']['DeleteCategory'](arg1, arg2);
}

export function ListCategories() {
  return window['go']['services']['CategoryService']['ListCategories']();
}

export function Startup(arg1) {
  return window['go']['services']['CategoryService']['Startup'](arg1);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['services']['CategoryService']['UpdateCategory'](arg1, arg2);
}
