// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateCategory(arg1:string):Promise<models.Category>;

export function DeleteCategory(arg1:number,arg2:boolean):Promise<void>;

export function ListCategories():Promise<Array<models.Category>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateCategory(arg1:number,arg2:string):Promise<void>;
