// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Port():Promise<number>;

export function Start():Promise<void>;

export function Stop(arg1:context.Context):Promise<void>;
