// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Port() {
  return window['go']['services']['MediaServer']['Port']();
}

export function Start() {
  return window['go']['services']['MediaServer']['Start']();
}

export function Stop(arg1) {
  return window['go']['services']['MediaServer']['Stop'](arg1);
}
