// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScript(arg1, arg2, arg3) {
  return window['go']['services']['ScriptService']['CreateScript'](arg1, arg2, arg3);
}

export function DeleteScript(arg1) {
  return window['go']['services']['ScriptService']['DeleteScript'](arg1);
}

export function ImportScripts(arg1) {
  return window['go']['services']['ScriptService']['ImportScripts'](arg1);
}

export function ListScripts(arg1, arg2) {
  return window['go']['services']['ScriptService']['ListScripts'](arg1, arg2);
}

export function SearchScripts(arg1) {
  return window['go']['services']['ScriptService']['SearchScripts'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['ScriptService']['Startup'](arg1);
}

export function UpdateScript(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ScriptService']['UpdateScript'](arg1, arg2, arg3, arg4);
}
