// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateScript(arg1:string,arg2:string,arg3:any,arg4:string):Promise<models.Script>;

export function DeleteScript(arg1:number):Promise<void>;

export function ImportScripts(arg1:Array<string>):Promise<number>;

export function ListScripts(arg1:number,arg2:number):Promise<Array<models.Script>>;

export function RevealInFileManager(arg1:string):Promise<void>;

export function SaveScriptImage(arg1:string,arg2:string):Promise<string>;

export function SearchScripts(arg1:string):Promise<Array<models.Script>>;

export function SelectAndSaveMedia():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateScript(arg1:number,arg2:string,arg3:string,arg4:any,arg5:string):Promise<models.Script>;
