// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Startup(arg1) {
  return window['go']['services']['TranslationService']['Startup'](arg1);
}

export function Translate(arg1, arg2, arg3) {
  return window['go']['services']['TranslationService']['Translate'](arg1, arg2, arg3);
}
