// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {context} from '../models';

export function GetStartApps():Promise<Array<utils.WindowInfo>>;

export function SetTarget(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartPolling():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopPolling():Promise<void>;
