// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartApps() {
  return window['go']['services']['WindowService']['GetStartApps']();
}

export function SetTarget(arg1) {
  return window['go']['services']['WindowService']['SetTarget'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['services']['WindowService']['Shutdown'](arg1);
}

export function StartPolling() {
  return window['go']['services']['WindowService']['StartPolling']();
}

export function Startup(arg1) {
  return window['go']['services']['WindowService']['Startup'](arg1);
}

export function StopPolling() {
  return window['go']['services']['WindowService']['StopPolling']();
}
